"""Second-pass verifiers for constrained OCR candidates."""

from __future__ import annotations

import json
from typing import Any


BINARY_SYSTEM_INSTRUCTION = """You are the FINAL conservative Vietnamese OCR verifier.

Each item contains exactly one proposed token-local change generated by local
OCR evidence. You have only two legal answers:
- CHANGE: the listed CANDIDATE is clearly the intended text in this context.
- KEEP: preserve OLD because evidence/context is ambiguous or the candidate
  could alter the author's intended wording.

You MUST NOT invent any third spelling, rewrite text, or explain your answer.
When uncertain choose KEEP.

Return one result for EVERY input item as JSON ONLY:
{"items":[{"id":"...","decision":"CHANGE"},{"id":"...","decision":"KEEP"}]}
"""


REVERSE_SYSTEM_INSTRUCTION = """You are a conservative Vietnamese OCR second-look verifier.

The first validator chose KEEP, but local OCR evidence still has one or more
plausible alternatives. Re-evaluate the token in CONTEXT and choose exactly one
listed choice_id. You may choose KEEP. You MUST NOT invent another spelling,
rewrite prose, or explain the answer. When uncertain choose KEEP.

Return one result for EVERY input item as JSON ONLY:
{"items":[{"id":"...","choice_id":"KEEP"},{"id":"...","choice_id":"C2"}]}
"""


def build_verifier_prompt(rows: list[dict[str, Any]]) -> str:
    return BINARY_SYSTEM_INSTRUCTION + "\nINPUT:\n" + json.dumps(rows, ensure_ascii=False, indent=2)


def build_reverse_prompt(rows: list[dict[str, Any]]) -> str:
    return REVERSE_SYSTEM_INSTRUCTION + "\nINPUT:\n" + json.dumps(rows, ensure_ascii=False, indent=2)
