"""Second-pass binary verifier for medium-strength OCR candidates."""

from __future__ import annotations

import json
from typing import Any


SYSTEM_INSTRUCTION = """You are the FINAL conservative Vietnamese OCR verifier.

Each item contains exactly one proposed token-local change that was generated by
local OCR evidence.  You have only two legal answers:
- CHANGE: the listed CANDIDATE is clearly the intended text in this context.
- KEEP: preserve OLD because the evidence/context is ambiguous or the candidate
  could alter the author's intended wording.

You MUST NOT invent any third spelling, rewrite text, or explain your answer.
When uncertain choose KEEP.

Return one result for EVERY input item as JSON ONLY:
{"items":[{"id":"...","decision":"CHANGE"},{"id":"...","decision":"KEEP"}]}
"""


def build_verifier_prompt(rows: list[dict[str, Any]]) -> str:
    return SYSTEM_INSTRUCTION + "\nINPUT:\n" + json.dumps(rows, ensure_ascii=False, indent=2)
